[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "limin-bench"
version = "0.3.1"
description = "A Python library for benchmarking and evaluating LLMs."
authors = [
    { name = "Titanom Solutions", email = "infrastructure@titanom.com" },
]
readme = "README.md"
dependencies = [
    "limin>=0.9.1",
    "limin-talk>=0.2.0",
]
requires-python = ">=3.10"

[tool.setuptools]
packages = ["limin_bench"]

[tool.setuptools.package-data]
limin_bench = ["py.typed", "data/*.json"]

[tool.mypy]
files = "limin_bench/"

[tool.ruff]
extend-exclude = ["**/*.ipynb"]
